musicApp/musicApp/album/urls.py
from django.urls import path, include

from musicApp.album.views import AlbumCreateView, AlbumDetailsView, AlbumUpdateView, AlbumDeleteView

urlpatterns = [
    path('add/', AlbumCreateView.as_view(), name='album-add'),
    path('<int:pk>/', include([
        path('details/', AlbumDetailsView.as_view(), name='album-details'),
        path('edit/', AlbumUpdateView.as_view(), name='album-edit'),
        path('delete/', AlbumDeleteView.as_view(), name='album-delete')
    ]))
]

musicApp/musicApp/common/urls.py
from django.urls import path
from musicApp.common.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

]

musicApp/musicApp/profile_user/urls.py
from django.urls import path, include
from musicApp.profile_user.views import ProfileDetailsView, ProfileDeleteView

urlpatterns = [
    path('details/', ProfileDetailsView.as_view(), name='profile-details'),
    path('delete/', ProfileDeleteView.as_view(), name='profile-delete'),
]

musicApp/musicApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('musicApp.common.urls')),
    path('album/', include('musicApp.album.urls')),
    path('profile/', include('musicApp.profile_user.urls'))
]

musicApp/musicApp/album/models.py
from django.core.validators import MinValueValidator
from django.db import models
from musicApp.album.choices import GenreChoices
from musicApp.profile_user.models import Profile


# Create your models here.
class Album(models.Model):
    MAX_LEN =30

    name = models.CharField(
        max_length=MAX_LEN,
        unique=True,
        verbose_name='Album Name'
    )

    artist_name = models.CharField(
        max_length=MAX_LEN,
        verbose_name='Artist'
    )

    genre = models.CharField(
        max_length=MAX_LEN,
        choices=GenreChoices.choices
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    image_url = models.URLField(
        verbose_name='Image URL',
    )

    price = models.FloatField(
        validators=[MinValueValidator(0.0)]
    )

    owner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='albums',
    )

musicApp/musicApp/profile_user/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from musicApp.profile_user.validators import UsernameValidator


# Create your models here.
class Profile(models.Model):
    MAX_LEN_USERNAME = 15
    MIN_LEN_USERNAME = 2

    username = models.CharField(
        max_length = MAX_LEN_USERNAME,
        validators=[
            MinLengthValidator(MIN_LEN_USERNAME),
            UsernameValidator()
        ],
    )

    email = models.EmailField()

    age = models.PositiveIntegerField(
        null=True,
        blank=True,
    )

musicApp/musicApp/profile_user/forms.py
from django import forms
from django.forms import ModelForm
from musicApp.profile_user.models import Profile


class ProfileCreateForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'age': forms.NumberInput(attrs={'placeholder': 'Age'}),
        }

musicApp/musicApp/album/views.py
from django.forms import modelform_factory
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from musicApp.album.mixins import AlbumFormMixin
from musicApp.album.models import Album
from musicApp.utils import get_profile


class AlbumCreateView(AlbumFormMixin, CreateView):
    model = Album
    fields = ['name', 'artist_name', 'genre', 'description', 'image_url', 'price']
    template_name = 'album/album-add.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.owner = get_profile()

        return super().form_valid(form)


class AlbumDetailsView(DetailView):
    model = Album
    template_name = 'album/album-details.html'


class AlbumUpdateView(AlbumFormMixin, UpdateView):
    model = Album
    fields = ['name', 'artist_name', 'genre', 'description', 'image_url', 'price']
    template_name = 'album/album-edit.html'
    success_url = reverse_lazy('index')


class AlbumDeleteView(DeleteView):
    model = Album
    form_class = modelform_factory(Album, fields=['name', 'artist_name', 'genre', 'description', 'image_url', 'price'])
    template_name = 'album/album-delete.html'
    success_url = reverse_lazy('index')

    # def get_initial(self):
    #     return self.object.__dict__
    #                                                     If ModelForm
    # def form_invalid(self, form):
    #     return self.form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.object
        return kwargs

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        for field in form.fields.values():
            field.widget.attrs['readonly'] = True

        return form

musicApp/musicApp/common/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import BaseFormView
from musicApp.album.models import Album
from musicApp.profile_user.forms import ProfileCreateForm
from musicApp.utils import get_profile


class IndexView(ListView, BaseFormView):
    model = Album
    form_class = ProfileCreateForm
    success_url = reverse_lazy('index')

    def get_template_names(self):
        profile = get_profile()

        if profile:
            return ['common/home-with-profile.html']
        return ['common/home-no-profile.html']


    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = get_profile()
        return context

musicApp/musicApp/profile_user/views.py
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView
from musicApp.profile_user.models import Profile
from musicApp.utils import get_profile


class ProfileDetailsView(DetailView):
    model = Profile
    template_name = 'profile/profile-details.html'

    def get_object(self, queryset=None):
        return get_profile()


class ProfileDeleteView(DeleteView):
    template_name = 'profile/profile-delete.html'
    success_url = reverse_lazy('index')

    def get_object(self, queryset=None):
        return get_profile()

musicApp/templates/album/album-add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <body>
    <div id="box">
      <!-- Main Content -->
      <!--Create Page-->
      <section class="createPage">
        <form action="{% url 'album-add' %}" method="post">
          <fieldset>
            <legend>Add Album</legend>
            <div class="container">
              <!-- Form for Adding Album -->
                {{ form }}
                {% csrf_token %}
              <button class="add-album" type="submit">Add New Album</button>
            </div>
          </fieldset>
        </form>
      </section>
    </div>
  </body>
{% endblock %}

musicApp/templates/album/album-delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="editPage">
    <form action="{% url 'album-delete' pk=album.pk %}" method="post">
      <fieldset>
        <legend>Delete Album</legend>
        <div class="container">
          <!-- Form for Deleting an Album -->
            {{ form }}
            {% csrf_token %}
          <!-- Button for Deleting an Album -->
          <button class="delete-album" type="submit">Delete Album</button>
        </div>
      </fieldset>
    </form>
  </section>
{% endblock %}

musicApp/templates/album/album-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section id="detailsPage">
    <div class="wrapper">
      <div class="albumCover">
        <!-- Album Image -->
        <img src="{{ album.image_url }}" alt="Cover Image" />
      </div>

      <div class="albumInfo">
        <div class="albumText">
          <!-- Album Info -->
          <h1>Name: {{ album.name }}</h1>
          <h3>Artist: {{ album.artist_name }}</h3>
          <h4>Genre: {{ album.genre}}</h4>
          <h4>Price: {{ album.price|floatformat:2 }}</h4>
          {%  if album %}  
              <p>
                {{ album.description }}
              </p>
          {% endif %}  
        </div>

        <div class="actionBtn">
          <!-- Album Buttons -->
          <a href="{% url 'album-edit' pk=album.pk %}" class="edit">Edit</a>
          <a href="{% url 'album-delete' pk=album.pk %}" class="remove">Delete</a>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

musicApp/templates/album/album-edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="editPage">
    <form action="{% url 'album-edit' pk=album.pk %}" method="post">
      <fieldset>
        <legend>Edit Album</legend>
        <div class="container">
          <!-- Form for Editing Album -->
            {{ form }}
            {% csrf_token %}
          <button class="edit-album" type="submit">Edit Album</button>
        </div>
      </fieldset>
    </form>
  </section>
{% endblock %}

musicApp/templates/common/home-no-profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <!-- Main Content -->
      <!--Home Page-->
      <div class="container-inline">
        <section id="welcomePage">
          <div id="welcome-message">
            <h1>Welcome to</h1>
            <h1>My Music App!</h1>
          </div>
          <div class="music-img">
            <img src="{% static 'images/musicIcons.webp' %}" alt="music-icon" />
          </div>
        </section>

        <!-- Registration -->
        <section id="registerPage">
          <form action="{% url 'index' %}" method="post">
            <fieldset>
              <legend>Profile</legend>
              <!-- Form for Registration -->
                {{ form }}
                {% csrf_token %}
                <button type="submit" class="register">Enter</button>
            </fieldset>
          </form>
        </section>
      </div>
{% endblock %}

musicApp/templates/common/home-with-profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section id="catalogPage">
    <!--  If No albums in catalog -->
    {% if album_list %}
        <h1>All Albums</h1>
      {% for album in album_list %}
        <div class="card-box">
          <img src="{{ album.image_url }}" alt="{{ album.description }}" />
          <div>
            <div class="text-center">
              <p class="name">Name: {{ album.name }}</p>
              <p class="artist">Artist: {{ album.artist_name }}</p>
              <p class="genre">Genre: {{ album.get_genre_display }}</p>
              <p class="price">Price: {{ album.price|floatformat:2 }}</p>
            </div>
            <div class="btn-group">
              <a href="{% url 'album-details' pk=album.pk %}">Details</a>
            </div>
          </div>
        </div>
      {% endfor %}    
      {% else %}
          <p>No Albums in Catalog!</p>
    {% endif %}
  </section>
{% endblock %}

musicApp/templates/common/nav.html
{% load static %}

<!-- Navigation Bar -->
      <header>
        <nav>
          <img src="{% static 'images/headphones.png' %}" alt="headphones" />
          <a href="{% url 'index' %}">Home</a>
          <ul></ul>
          <ul>
            <!--Only for user with created profile-->
              {% if profile %}
                <li><a href="{% url 'album-add' %}">Create Album</a></li>
                <li><a href="{% url 'profile-details' %}">Profile</a></li>
              {% endif %}
          </ul>
        </nav>
      </header>
      <!-- End Navigation Bar -->